// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/location': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/location').default>>>>
    }
    '/api/weather': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/weather').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.13.0_sass@1.77.8_vite@5.4.2/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+image@1.8.1/node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}